name: Run Package Script
on:
  push:
    branches:
      - master
jobs:
  run-package-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Ensure script is executable
        run: chmod +x .github/workflows/package_script.sh
      
      - name: Run package script
        run: bash .github/workflows/package_script.sh
      
      - name: Check for changes
        id: git-check
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config user.name "Bitcion"
          git config user.email "bitcoinismine@gmail.com"
          git commit -m "Update generated files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
