name: Run GFWList script

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          cd Bitcion/zaixiantuoguan
          sh run_gfwlist.sh
      - name: Commit files
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update GFWList"
          add: "*.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
